# This function will create a new individual provider record from the markdown text generated by the image_to_markdown function. This fucntion will only intake the markdown text and will not intake any other information.  Then this will create a new individual provider record in the database with only a provider ID and the markdown text populated.  

# The below fields must be populated in the individual provider record so they will have placeholder values:

# NPI = "To be assigned"
# First Name = "New Provider from Image"
# Last Name = "Created at Current Time on Current Date"

# npi = db.Column(db.Text, nullable=False)
# first_name = db.Column(db.Text, nullable=False)
# last_name = db.Column(db.Text, nullable=False)


from datetime import datetime
from models.db import db
from models.provider import IndividualProvider

def create_individual_provider_from_markdown(markdown_text: str) -> IndividualProvider:
    """
    Creates a new individual provider record from markdown text with placeholder values.
    Only populates provider ID and markdown text, with placeholder values for required fields.

    Args:
        markdown_text: The markdown text generated from the image

    Returns:
        IndividualProvider: The newly created provider record
    """

    # Create timestamp for the placeholder last name
    current_time = datetime.now().strftime("%B %d, %Y at %I:%M %p")

    # Create new provider with required placeholder values
    new_provider = IndividualProvider(
        npi="To be assigned",
        first_name="New Provider from Image",
        last_name=f"Created at {current_time}",
        provider_enrollment_form_markdown_text=markdown_text
    )

    # Add and commit to database
    db.session.add(new_provider)
    db.session.commit()

    return new_provider