# This function will create a new individual provider record from the markdown text generated by the image_to_markdown function. This fucntion will only intake the markdown text and will not intake any other information.  Then this will create a new individual provider record in the database with only a provider ID and the markdown text populated.  

# The below fields must be populated in the individual provider record so they will have placeholder values:

# NPI = "To be assigned"
# First Name = "New Provider from Image"
# Last Name = "Created at Current Time on Current Date"

# npi = db.Column(db.Text, nullable=False)
# first_name = db.Column(db.Text, nullable=False)
# last_name = db.Column(db.Text, nullable=False)

