# I'm going to create this new facets.json to markdown file, which will sit next to the provider to facets.py file in my hierarchy.  Similarly, it will work by intaking a provider ID, and it will then use that database ID for a provider to read the facets.provider.tables.json,  and then it will populate the provider facets markdown field and then return a success message. Can you show me what this complete file will look like?

# facets_json_to_markdown.py

# This function will be called to convert the provider facets tables, which is stored in JSON format, into a readable markdown format that gives an overview of which facets database tables will be loaded from this record and the corresponding related tables.

# This markdown will be somewhat in plain English language of which provider records will be loaded to the facets database tables.  It will say the full table names, such as CMC, PRP, underscore PRPR, underscore P-R-O-V, and will give explanations for what the table is.  And then it will say like that CMC, underscore P-R-P-R table contains the core individual provider record.  Then it will spell out which tables contain relationships, which tables maintain addresses, and which tables contain provider group and hospital information, and which tables contain network information.

# this is a sample of what the facets JSON looks like:

# {'PRAC': [{'PRPR_ID': '1831539220', 'PRAC_SEQ': 1, 'PRAC_EFF_DT': '2025-04-30', 'PRAC_SPEC_CD': 'Internal Medicine', 'PRAC_TERM_DT': '9999-12-31', 'PRAC_TYPE_CD': 'Prof'}], 'PRAD': [{'PRPR_ID': '1831539220', 'PRAD_FAX': None, 'PRAD_ZIP': '83706', 'PRAD_CITY': 'Boise', 'PRAD_TYPE': 'PRM', 'PRAD_ADDR1': '3550 W Americana Ter', 'PRAD_ADDR2': None, 'PRAD_PHONE': '208-615-4940', 'PRAD_STATE': 'ID', 'PRAD_EFF_DT': '2025-04-30', 'PRAD_TERM_DT': '9999-12-31'}], 'PRAF': [{'PRAF_EFF_DT': '2023-01-01', 'PRAF_ROLE_CD': 'MN', 'PRAF_TERM_DT': '9999-12-31', 'PRPR_ID_CHILD': '1831539220', 'PRPR_ID_PARENT': 'G-000003'}], 'PRNT': [], 'PRPR': [{'PRPR_ID': '1831539220', 'PRPR_NPI': '1831539220', 'PRPR_EFF_DT': '2025-04-30', 'PRPR_ENTITY': 'I', 'PRPR_TAX_ID': None, 'PRPR_TERM_DT': '9999-12-31', 'PRPR_MCTR_STS': 'ACTV', 'PRPR_NAME_LAST': 'Schwind', 'PRPR_NAME_FIRST': 'Adam'}, {'PRPR_ID': 'G-000003', 'PRPR_NPI': None, 'PRPR_EFF_DT': '2025-04-30', 'PRPR_ENTITY': 'G', 'PRPR_TAX_ID': 'MDI789', 'PRPR_TERM_DT': '9999-12-31', 'PRPR_MCTR_STS': 'ACTV', 'PRPR_NAME_LAST': 'Medical Directors of Idaho'}]}