"""Initial migration

Revision ID: 56e72c42ed88
Revises: 
Create Date: 2025-04-27 10:28:15.621352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56e72c42ed88'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('county',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospital',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('network',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('county_network',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('county_id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['county.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['network_id'], ['network.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospital_network',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['network_id'], ['network.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hospital_network')
    op.drop_table('county_network')
    op.drop_table('network')
    op.drop_table('hospital')
    op.drop_table('county')
    # ### end Alembic commands ###
